# Generated by Django 4.0.4 on 2023-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.FileField(upload_to='')),
                ('posts', models.FileField(upload_to='')),
                ('stories', models.FileField(upload_to='')),
                ('likes', models.FileField(upload_to='')),
                ('comments', models.FileField(upload_to='')),
                ('images', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
            },
        ),
    ]
