# Generated by Django 4.0.4 on 2023-05-08 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='comments',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='images',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='likes',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='posts',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stories',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='users',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
