# Generated by Django 4.0.4 on 2023-06-01 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0002_alter_upload_comments_alter_upload_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='comments',
            field=models.FileField(blank=True,
                                   help_text='File Type: CSV; Format: Username*, Commented_Username*, Post_Date* (YYYY-MM-DD HH:MM:SS), Comment_Date* (YYYY-MM-DD HH:MM:SS)',
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='images',
            field=models.FileField(blank=True,
                                   help_text="File Type: ZIP; Needs to be uploaded, if any Pictures are uploaded. All Image paths are relative to root folder (don't include .zip).",
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='likes',
            field=models.FileField(blank=True,
                                   help_text='File Type: CSV; Format: Username*, Liked_Username*, Post_Date* (YYYY-MM-DD HH:MM:SS), Like_Date* (YYYY-MM-DD HH:MM:SS)',
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='posts',
            field=models.FileField(blank=True,
                                   help_text='File Type: CSV; Format: Username*, Path_Picture*, Caption*, Date* (YYYY-MM-DD HH:MM:SS)',
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stories',
            field=models.FileField(blank=True,
                                   help_text='File Type: CSV; Format: Username*, Path_Picture*, Date* (YYYY-MM-DD HH:MM:SS)',
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='users',
            field=models.FileField(blank=True,
                                   help_text='File Type: CSV; Format: Username*, Password*, Name, Surname, Bio, Path_Profile_Picture',
                                   upload_to='', validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
