# Generated by Django 4.0.4 on 2023-06-18 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0003_alter_upload_comments_alter_upload_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='advertisements',
            field=models.FileField(blank=True, help_text='upload_ads_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='ads_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='comments',
            field=models.FileField(blank=True, help_text='upload_comments_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])],
                                   verbose_name='comments_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='images',
            field=models.FileField(blank=True, help_text='upload_images_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='images_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='likes',
            field=models.FileField(blank=True, help_text='upload_likes_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='likes_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='posts',
            field=models.FileField(blank=True, help_text='upload_posts_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='posts_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stories',
            field=models.FileField(blank=True, help_text='upload_stories_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])],
                                   verbose_name='stories_file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='users',
            field=models.FileField(blank=True, help_text='upload_users_help', upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='users_file'),
        ),
    ]
