# Generated by Django 5.1.1 on 2025-03-06 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_advertisements_alter_upload_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='exercises',
            field=models.FileField(blank=True, help_text='upload_exercises_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='exercises_file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='multipleChoiceOptions',
            field=models.FileField(blank=True, help_text='upload_multipleChoiceOptions_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='multipleChoiceOptions_file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='sections',
            field=models.FileField(blank=True, help_text='upload_sections_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='sections_file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='tasks',
            field=models.FileField(blank=True, help_text='upload_tasks_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='tasks_file'),
        ),
    ]
