# Generated by Django 5.1.1 on 2025-03-09 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_upload_exercises_upload_multiplechoiceoptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='features',
            field=models.FileField(blank=True, help_text='upload_features_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='features_file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='points',
            field=models.FileField(blank=True, help_text='upload_points_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='points_file'),
        ),
        migrations.AddField(
            model_name='upload',
            name='userFeatures',
            field=models.FileField(blank=True, help_text='upload_userFeatures_help', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='userFeatures_file'),
        ),
    ]
