# Generated by Django 5.1.1 on 2024-09-30 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False, verbose_name='submission reviewed')),
                ('feedback', models.TextField(blank=True, verbose_name='submission feedback')),
                ('correct', models.BooleanField(default=False, verbose_name='submission correct')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='section name')),
                ('description', models.TextField(blank=True, verbose_name='section description')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workbook.submission')),
                ('choices', models.JSONField(verbose_name='selected choices')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workbook.submission',),
        ),
        migrations.CreateModel(
            name='TextAnswerSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workbook.submission')),
                ('answer', models.TextField(blank=True, verbose_name='submitted answer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workbook.submission',),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='exercise title')),
                ('description', models.TextField(blank=True, verbose_name='exercise description')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workbook.section', verbose_name='parent section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='task title')),
                ('information', models.TextField(blank=True, verbose_name='task information')),
                ('type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT_ANSWER', 'Text Answer'), ('INTERACTIVE', 'Interactive')], default='TEXT_ANSWER', max_length=20, verbose_name='task type')),
                ('minimum_answer_length', models.IntegerField(default=0, verbose_name='minimum answer length')),
                ('correct_answer', models.TextField(blank=True, null=True, verbose_name='correct answer')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workbook.exercise', verbose_name='parent exercise')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workbook.task', verbose_name='task'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workbook.task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'task')},
        ),
    ]
