# Generated by Django 5.1.1 on 2024-10-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workbook.submission')),
                ('type', models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', max_length=30, verbose_name='action type')),
                ('target_count', models.IntegerField(default=1, verbose_name='target action count')),
                ('current_count', models.IntegerField(default=0, verbose_name='current action count')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workbook.submission',),
        ),
        migrations.AddField(
            model_name='task',
            name='interaction_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', max_length=30, verbose_name='interaction type'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(default=1, verbose_name='target action count'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT_ANSWER', 'Text Answer'), ('INTERACTIVE', 'Interactive')], default='TEXT_ANSWER', help_text='Type-specific fields can be accessed after creating the task, in edit mode. For example the options for multiple choice tasks can be added there.', max_length=20, verbose_name='task type'),
        ),
    ]
