# Generated by Django 5.1.1 on 2024-10-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0002_interactivesubmission_task_interaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactivesubmission',
            old_name='type',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', max_length=30, verbose_name='action type'),
        ),
    ]
