# Generated by Django 5.1.1 on 2024-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0003_rename_type_interactivesubmission_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for successfully completing this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', help_text='Not yet implemented, DO NOT USE: CREATE_ADVERTISEMENT.', max_length=30, verbose_name='action type'),
        ),
    ]
