# Generated by Django 5.1.1 on 2024-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0004_submission_awarded_points_task_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workbook/', verbose_name='task image'),
        ),
    ]
