# Generated by Django 5.1.1 on 2024-11-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0005_task_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Ordering of the tasks'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], default='TEXT', max_length=10)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='content_blocks/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Ordering of the content blocks')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='workbook.exercise', verbose_name='parent exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
