# Generated by Django 5.1.1 on 2024-11-07 18:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0006_alter_task_options_task_order_contentblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='information',
        ),
        migrations.AddField(
            model_name='task',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='task body'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', help_text='Specify action type for interactive task.', max_length=30, verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT_ANSWER', 'Text Answer'), ('INTERACTIVE', 'Interactive'), ('CONTENT', 'Content')], default='TEXT_ANSWER', help_text='Type-specific fields can be accessed after creating the task, in edit mode. For example the options for multiple choice tasks can be added there.', max_length=20, verbose_name='task type'),
        ),
    ]
