# Generated by Django 5.1.1 on 2024-11-10 23:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0008_alter_exercise_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='Content to displayed above all tasks on the exercise page.', verbose_name='exercise description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the exercise inside the parent section. Reorder exercises by editing the section.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the section inside the workbook. Reorder sections in the Sections admin.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, help_text='The points earned by the student for this submission. It is set automatically once the submission is marked as correct.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(default=False, help_text='Tick this box if the submission is correct.', verbose_name='submission correct'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Optional feedback for the student who made the submission.', verbose_name='submission feedback'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Tick this box after you have reviewed the submission.', verbose_name='submission reviewed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', help_text='Specify the action the student has to perform.', max_length=30, verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Set the content to be displayed for the task.', null=True, verbose_name='task body'),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Set a correct answer for this task. The student have to submit the exact same answer to complete the task. If set, the correction is done automatically.', null=True, verbose_name='correct answer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exercise',
            field=models.ForeignKey(help_text='Assigns the task to an exercise. If you change the initially assigned exercise, make sure to check the correct ordering.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workbook.exercise', verbose_name='parent exercise'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Fast upload of an image outside the task body.', null=True, upload_to='workbook/', verbose_name='task image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='minimum_answer_length',
            field=models.IntegerField(default=0, help_text='The student has to type (at least) the specified amount of characters to make a submission.', verbose_name='minimum answer length'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the task inside the parent exercise.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded to the user for successfully completing the task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(default=1, help_text='The student has to perform the action this many times to complete the task.', verbose_name='target action count'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT_ANSWER', 'Text Answer'), ('INTERACTIVE', 'Interactive'), ('CONTENT', 'Content')], default='CONTENT', help_text='Choose the task type upon creation. Do NOT change this later!', max_length=20, verbose_name='task type'),
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
