# Generated by Django 5.1.1 on 2024-11-13 20:26

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0009_alter_exercise_description_alter_exercise_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order'], 'verbose_name': 'exercise_singular', 'verbose_name_plural': 'exercise_plural'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section_singular', 'verbose_name_plural': 'section_plural'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'submission_singular', 'verbose_name_plural': 'submission_plural'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'task_singular', 'verbose_name_plural': 'task_plural'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='Description will be displayed on the top of the exercise page.', verbose_name='exercise_description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the exercise inside the parent section. Reorder exercises by editing the section.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plural', to='workbook.section', verbose_name='section_singular'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255, verbose_name='exercise_title'),
        ),
        migrations.AlterField(
            model_name='interactivesubmission',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', max_length=30, verbose_name='action_type'),
        ),
        migrations.AlterField(
            model_name='interactivesubmission',
            name='current_count',
            field=models.IntegerField(default=0, verbose_name='current_action_count'),
        ),
        migrations.AlterField(
            model_name='interactivesubmission',
            name='target_count',
            field=models.IntegerField(default=1, verbose_name='target_action_count'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='is_correct'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_plural', to='workbook.task'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='text',
            field=models.CharField(max_length=200, verbose_name='option_singular'),
        ),
        migrations.AlterField(
            model_name='multiplechoicesubmission',
            name='choices',
            field=models.JSONField(verbose_name='selected_choices'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='section_description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the section inside the workbook. Reorder sections in the Sections admin.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, verbose_name='section_title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='awarded_points',
            field=models.PositiveIntegerField(default=0, help_text='The points earned by the student for this submission. It is set once the submission is marked as correct and the student has claimed the points.', verbose_name='awarded_points'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='correct',
            field=models.BooleanField(default=False, help_text='Tick this box if the submission is correct.', verbose_name='submission_correct'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Optional feedback for the student.', verbose_name='submission_feedback'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Tick this box after you have reviewed the submission.', verbose_name='submission_reviewed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submitted_at'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workbook.task', verbose_name='task_singular'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], default='CREATE_POST', help_text='Specify the action the student has to perform.', max_length=30, verbose_name='action_type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Set the content to be displayed for the task.', null=True, verbose_name='task_body'),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Set a correct answer for this task. The student have to submit the exact same answer to complete the task. If set, the correction is done automatically.', null=True, verbose_name='correct_answer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exercise',
            field=models.ForeignKey(help_text='Assigns the task to an exercise. If you change the initially assigned exercise, make sure to check the correct ordering.', on_delete=django.db.models.deletion.CASCADE, related_name='task_plural', to='workbook.exercise', verbose_name='exercise_singular'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload of an image, which will be displayed above the task body.', null=True, upload_to='workbook/', verbose_name='task_image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='minimum_answer_length',
            field=models.IntegerField(default=0, help_text='The student has to type (at least) the specified amount of characters to make a submission.', verbose_name='minimum_answer_length'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Position of the task inside the parent exercise.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded to the student for successfully completing the task.', verbose_name='point_plural'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(default=1, help_text='The student has to perform the action this many times to complete the task.', verbose_name='target_action_count'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='task_title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT_ANSWER', 'Text Answer'), ('INTERACTIVE', 'Interactive'), ('CONTENT', 'Content')], default='CONTENT', help_text='Choose the task type upon creation. Do NOT change this later!', max_length=20, verbose_name='task_type'),
        ),
        migrations.AlterField(
            model_name='textanswersubmission',
            name='answer',
            field=models.TextField(blank=True, verbose_name='submitted_answer'),
        ),
    ]
