# Generated by Django 5.1.1 on 2024-11-13 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0010_alter_exercise_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workbook.section', verbose_name='section_singular'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workbook.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exercise',
            field=models.ForeignKey(help_text='Assigns the task to an exercise. If you change the initially assigned exercise, make sure to check the correct ordering.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workbook.exercise', verbose_name='exercise_singular'),
        ),
    ]
