# Generated by Django 5.1.1 on 2024-11-19 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0011_alter_exercise_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image_upload',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
