# Generated by Django 5.1.1 on 2024-11-20 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0012_task_image_data_task_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AlterField(
            model_name='task',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='task_image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_upload',
            field=models.FileField(blank=True, help_text='upload_task_image_help', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
