# Generated by Django 5.1.1 on 2024-11-25 02:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0013_remove_task_image_alter_task_image_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceoption',
            name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='body',
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='option',
            field=models.CharField(default='', max_length=255, verbose_name='option_singular'),
        ),
        migrations.AddField(
            model_name='task',
            name='lower_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Set the text to be displayed under the (optional) task image.', null=True, verbose_name='task_lower_text'),
        ),
        migrations.AddField(
            model_name='task',
            name='upper_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Set the text to be displayed above the (optional) task image.', null=True, verbose_name='task_upper_text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='task_title'),
        ),
    ]
