# Generated by Django 5.1.1 on 2024-11-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0014_remove_multiplechoiceoption_text_remove_task_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lower_text',
            field=models.TextField(blank=True, help_text='Set the text to be displayed under the (optional) task image.', null=True, verbose_name='task_lower_text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='upper_text',
            field=models.TextField(blank=True, help_text='Set the text to be displayed above the (optional) task image.', null=True, verbose_name='task_upper_text'),
        ),
    ]
