# Generated by Django 5.1.1 on 2024-12-23 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0015_alter_task_lower_text_alter_task_upper_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_upload',
            field=models.FileField(blank=True, help_text='upload_task_image_help', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='image_upload'),
        ),
    ]
