# Generated by Django 5.1.1 on 2025-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0016_alter_task_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(blank=True, choices=[('CREATE_POST', 'Create Post'), ('LIKE_POST', 'Like Post'), ('COMMENT_POST', 'Comment Post'), ('FOLLOW', 'Follow'), ('CREATE_STORY', 'Create Story'), ('CREATE_ADVERTISEMENT', 'Create Advertisement'), ('EDIT_PROFILE', 'Edit Profile')], help_text='Specify the action the student has to perform.', max_length=30, null=True, verbose_name='action_type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='minimum_answer_length',
            field=models.IntegerField(blank=True, help_text='The student has to type (at least) the specified amount of characters to make a submission.', null=True, verbose_name='minimum_answer_length'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(blank=True, help_text='The student has to perform the action this many times to complete the task.', null=True, verbose_name='target_action_count'),
        ),
    ]
