# Generated by Django 5.1.1 on 2025-03-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0017_alter_task_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
