# Generated by Django 4.0.4 on 2023-04-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('post_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='post.post')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Werbung',
                'verbose_name_plural': 'Werbungen',
            },
            bases=('post.post',),
        ),
    ]
