# Generated by Django 4.0.4 on 2023-05-15 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0003_alter_comment_created_on_alter_like_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_deleted',
        ),
    ]
