# Generated by Django 4.0.4 on 2023-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0004_remove_story_expiration_time_remove_story_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NA', 'Na')],
                                   null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='interests',
            field=models.TextField(default='cars'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_age_high',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_age_low',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
