# Generated by Django 4.0.4 on 2023-05-27 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0005_advertisement_gender_advertisement_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NA', 'Na')], max_length=10),
                                                            null=True, size=None),
        ),
    ]
