# Generated by Django 4.0.4 on 2023-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0006_alter_advertisement_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
