# Generated by Django 4.0.4 on 2023-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0007_alter_advertisement_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='target_age_none',
            field=models.BooleanField(default=False),
        ),
    ]
