# Generated by Django 4.0.4 on 2023-05-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0008_advertisement_target_age_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='no_interests',
            field=models.BooleanField(default=False),
        ),
    ]
