# Generated by Django 4.0.4 on 2023-06-18 17:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_advertisement_no_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'action_singular', 'verbose_name_plural': 'action_plural'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'advertisement_singular', 'verbose_name_plural': 'advertisement_plural'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment_singular', 'verbose_name_plural': 'comment_plural'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like_singular', 'verbose_name_plural': 'like_plural'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post_singular', 'verbose_name_plural': 'post_plural'},
        ),
        migrations.AlterModelOptions(
            name='storyview',
            options={'verbose_name': 'story_view_singular', 'verbose_name_plural': 'story_view_plural'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('following', 'following'), ('like', 'like'), ('comment', 'comment')],
                                   max_length=255, verbose_name='action_type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='action',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='actions', to='post.post', verbose_name='post_singular'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_actions',
                                    to=settings.AUTH_USER_MODEL, verbose_name='target_user'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='gender',
            field=models.TextField(null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='interests',
            field=models.TextField(null=True, verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='keyword',
            field=models.TextField(null=True, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='no_interests',
            field=models.BooleanField(default=False, verbose_name='no interests'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='target_age_high',
            field=models.PositiveIntegerField(default=1000, verbose_name='target_age_high'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='target_age_low',
            field=models.PositiveIntegerField(default=0, verbose_name='target_age_low'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='target_age_none',
            field=models.BooleanField(default=False, verbose_name='target_age_none'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='comment_content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post',
                                    verbose_name='post_singular'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='like',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_set',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post',
                                    verbose_name='post_singular'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='post_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='post_hashtags', to='post.hashtag',
                                         verbose_name='hashtags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_date'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(verbose_name='story_content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='story',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_set',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='storyview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_story_set',
                                    to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
