# Generated by Django 4.0.4 on 2023-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0010_alter_action_options_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='interests',
            field=models.TextField(verbose_name='interests'),
        ),
    ]
