# Generated by Django 4.0.4 on 2023-08-03 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0011_alter_advertisement_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag', 'verbose_name_plural': 'Hashtags'},
        ),
    ]
