# Generated by Django 4.0.4 on 2023-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_imagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_preview',
            field=models.TextField(blank=True, verbose_name='content_preview'),
        ),
    ]
