# Generated by Django 4.0.4 on 2023-09-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_content_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetag',
            old_name='x_position',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='imagetag',
            old_name='y_position',
            new_name='y',
        ),
    ]
