# Generated by Django 5.1.1 on 2025-02-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_rename_x_position_imagetag_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='keyword',
            field=models.TextField(blank=True, null=True, verbose_name='keyword'),
        ),
    ]
