# Generated by Django 5.1.1 on 2026-04-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_advertisement_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='like_count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='comment_count')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='post.post')),
            ],
        ),
    ]
