# Generated by Django 5.1.1 on 2026-04-21

import base64
import binascii

import django.core.validators
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations, models


def _tenant_schema_name(schema_editor):
    return getattr(schema_editor.connection, "schema_name", None) or "public"


def migrate_story_images_to_storage(apps, schema_editor):
    Story = apps.get_model("post", "Story")
    db_alias = schema_editor.connection.alias

    queryset = Story.objects.using(db_alias).filter(content_upload__isnull=True)

    for story in queryset.iterator():
        raw_content = (story.content or "").strip()

        if not raw_content:
            continue

        if raw_content.startswith(("http://", "https://")):
            continue

        if raw_content.startswith("data:") and "," in raw_content:
            raw_content = raw_content.split(",", 1)[1]

        try:
            image_bytes = base64.b64decode(raw_content)
        except (binascii.Error, ValueError):
            continue

        tenant_schema = _tenant_schema_name(schema_editor)
        upload_name = f"{tenant_schema}/stories/migrated-story-{story.pk}.jpg"
        saved_name = default_storage.save(upload_name, ContentFile(image_bytes))

        story.content_upload = saved_name
        story.content = default_storage.url(saved_name)
        story.save(update_fields=["content_upload", "content"])


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0017_post_content_upload_and_migrate_images_to_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="content_upload",
            field=models.FileField(
                blank=True,
                null=True,
                max_length=255,
                upload_to="stories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="image_upload",
            ),
        ),
        migrations.RunPython(migrate_story_images_to_storage, reverse_noop),
    ]
