# Generated by Django 4.0.4 on 2022-12-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_allowed', models.BooleanField(default=True)),
                ('is_private_account', models.BooleanField(default=False)),
                ('allow_tags_from', models.CharField(
                    choices=[('everyone', 'Everyone'), ('following', 'Only Followings'), ('noone', 'No One')],
                    default='everyone', max_length=10)),
                ('allow_mentions_from', models.CharField(
                    choices=[('everyone', 'Everyone'), ('following', 'Only Followings'), ('noone', 'No One')],
                    default='everyone', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('bio', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_allowed', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('following_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonniert',
                'verbose_name_plural': 'Abonniert',
            },
        ),
    ]
