# Generated by Django 4.0.4 on 2023-02-26 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'following_user')},
        ),
    ]
