# Generated by Django 4.0.4 on 2023-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_following_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
