# Generated by Django 4.0.4 on 2023-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_profile_age_alter_profile_bio_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
