# Generated by Django 4.0.4 on 2023-03-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_alter_profile_bio_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], null=True),
        ),
    ]
