# Generated by Django 4.0.4 on 2023-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(null=True),
        ),
    ]
