# Generated by Django 4.0.4 on 2023-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='newsfeed_algorithm',
            field=models.TextField(choices=[('ALGORITHM_1', 'Algorithm 1'), ('ALGORITHM_2', 'Algorithm 2'),
                                            ('ALGORITHM_3', 'Algorithm 3')], default='ALGORITHM_1'),
        ),
    ]
