# Generated by Django 4.0.4 on 2023-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_setting_newsfeed_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NA', 'Na')],
                                   null=True),
        ),
    ]
