# Generated by Django 4.0.4 on 2023-06-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name': 'following_singular', 'verbose_name_plural': 'following_plural'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile_singular', 'verbose_name_plural': 'profile_plural'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'settings_singular', 'verbose_name_plural': 'settings_plural'},
        ),
        migrations.AlterField(
            model_name='following',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers',
                                    to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
        migrations.AlterField(
            model_name='following',
            name='notification_allowed',
            field=models.BooleanField(default=True, verbose_name='notification_allowed'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings',
                                    to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NA', 'Na')],
                                   null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(null=True, verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.TextField(null=True, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                       to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_mentions_from',
            field=models.CharField(
                choices=[('everyone', 'Everyone'), ('following', 'Only Followings'), ('noone', 'No One')],
                default='everyone', max_length=10, verbose_name='allow_mentions_from'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_tags_from',
            field=models.CharField(
                choices=[('everyone', 'Everyone'), ('following', 'Only Followings'), ('noone', 'No One')],
                default='everyone', max_length=10, verbose_name='allow_tags_from'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='comment_allowed',
            field=models.BooleanField(default=True, verbose_name='comments_allowed'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_private_account',
            field=models.BooleanField(default=False, verbose_name='is_priv_acc'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='newsfeed_algorithm',
            field=models.TextField(choices=[('ALGORITHM_1', 'Algorithm 1'), ('ALGORITHM_2', 'Algorithm 2'),
                                            ('ALGORITHM_3', 'Algorithm 3')], default='ALGORITHM_1',
                                   verbose_name='newsfeed_alg'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings',
                                       to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
    ]
