# Generated by Django 4.0.4 on 2023-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0009_alter_following_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NA', 'Na')],
                                   default='NA', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.TextField(blank=True, null=True, verbose_name='picture'),
        ),
    ]
