# Generated by Django 4.0.4 on 2023-08-31 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_alter_profile_age_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='allow_mentions_from',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_private_account',
        ),
    ]
