# Generated by Django 5.1.1 on 2024-11-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoints',
            old_name='balance',
            new_name='points',
        ),
    ]
