# Generated by Django 5.1.1 on 2024-11-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_balance_userpoints_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
