# Generated by Django 5.1.1 on 2024-11-21 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_userpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_post', models.DateTimeField(blank=True, null=True, verbose_name='last_post_created_on')),
                ('last_story', models.DateTimeField(blank=True, null=True, verbose_name='last_story_created_on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
