# Generated by Django 5.1.1 on 2025-02-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='newsfeed_affinity_comment_weight',
            field=models.FloatField(default=2, verbose_name='newsfeed_affinity_comment_weight'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_affinity_like_weight',
            field=models.FloatField(default=1, verbose_name='newsfeed_affinity_like_weight'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_post_comment_weight',
            field=models.FloatField(default=2, verbose_name='newsfeed_post_comment_weight'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_post_like_weight',
            field=models.FloatField(default=1, verbose_name='newsfeed_post_like_weight'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_time_decay_base_factor',
            field=models.FloatField(default=0.995, verbose_name='newsfeed_time_decay_base_factor'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_xray_mode',
            field=models.BooleanField(default=False, verbose_name='newsfeed_xray_mode'),
        ),
    ]
