# Generated by Django 5.1.1 on 2025-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_setting_newsfeed_affinity_comment_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='newsfeed_time_decay_base_factor',
            field=models.FloatField(default=0.005, verbose_name='newsfeed_time_decay_base_factor'),
        ),
    ]
