# Generated by Django 5.1.1 on 2025-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_setting_newsfeed_time_decay_base_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='newsfeed_advertisement_frequency',
            field=models.IntegerField(default=5, verbose_name='newsfeed_advertisement_frequency'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_social_graph_mode',
            field=models.BooleanField(default=False, verbose_name='newsfeed_social_graph_mode'),
        ),
    ]
