# Generated by Django 5.1.1 on 2025-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_setting_newsfeed_advertisement_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='newsfeed_affinity_follower_weight',
            field=models.FloatField(default=0, verbose_name='newsfeed_affinity_follower_weight'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_followed_only_mode',
            field=models.BooleanField(default=False, verbose_name='newsfeed_followed_only_mode'),
        ),
        migrations.AddField(
            model_name='setting',
            name='newsfeed_show_own_posts',
            field=models.BooleanField(default=True, verbose_name='newsfeed_show_own_posts'),
        ),
    ]
