# Generated by Django 5.1.1 on 2026-04-15 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_setting_newsfeed_affinity_follower_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('affinity_like_count', models.IntegerField(verbose_name='affinity_like_count')),
                ('affinity_comment_count', models.IntegerField(verbose_name='affinity_comment_count')),
                ('follows', models.BooleanField(verbose_name='follows_user')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to=settings.AUTH_USER_MODEL, verbose_name='from_user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_affinities', to=settings.AUTH_USER_MODEL, verbose_name='to_user')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('affinity_like_count__gte', 0)), name='affinity_like_count_non_negative'), models.CheckConstraint(condition=models.Q(('affinity_comment_count__gte', 0)), name='affinity_comment_count_non_negative')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
