# Generated by Django 5.1.1 on 2026-05-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.TextField(blank=True, null=True, verbose_name='background picture'),
        ),
    ]
