"""
Django settings for InstaClone project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from os import environ
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l#6^j#z5@9h53t8$&d+jl(vft_o@a610b8*a^_=vss@)fy$hfc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if os.getenv("DEBUG") == "True":
    DEBUG = True

# DEBUG = True
# DEBUG_PROPAGATE_EXCEPTIONS = True

# Only for local development
# LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'handlers': {
#       'file': {
#          'level': 'DEBUG',
#          'class': 'logging.FileHandler',
#          'filename': '/tmp/instaclone/debug.log',
#       },
#    },
#    'loggers': {
#       'django': {
#          'handlers': ['file'],
#          'level': 'DEBUG',
#          'propagate': True,
#       },
#    },
# }

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    # Production
    "https://*.instaclone.de",
    # Development
    "https://*.dev.instaclone.de",
    # Local development with Vite
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # Local admin access
    "http://127.0.0.1:8000",
    ]

# Application definition

SHARED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'adminsortable2', # Used in workbook admin page to drag-and-drop sort with SortableInlineAdminMixin
    'corsheaders',
    'channels',
    'django_tenants',
    'tenants',
    'django_ckeditor_5', # Rich text editor
    # Custom instaclone apps
    'user',
    'post',
    'analytic',
    'upload',
    'export',
    'report',
    'workbook',
    'rewards'
]

TENANT_APPS = [
    'user',
    'post',
    'analytic',
    'upload',
    'export',
    'report',
    'workbook',
    'rewards',

    'django.contrib.admin',
    'django.contrib.auth'
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',

]

ROOT_URLCONF = 'InstaClone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InstaClone.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": environ.get("DB_NAME", "postgres"),
        "USER": environ.get("DB_USER", "postgres"),
        "PASSWORD": environ.get("DB_PASSWORD", ""),
        "HOST": environ.get("DB_HOST", "db"),
        "PORT": environ.get("DB_PORT", "5432"),
        # Keep DB connections alive for 10 minutes instead of closing after every request (default 0).
        # Each gunicorn worker holds one persistent connection to PostgreSQL.
        "CONN_MAX_AGE": int(environ.get("DB_CONN_MAX_AGE", "600")),
        # Verify reused connections are still alive before using them.
        "CONN_HEALTH_CHECKS": True,
    }
}

DATABASE_ROUTERS = {
    "django_tenants.routers.TenantSyncRouter"
}

TENANT_MODEL = "tenants.Client"

TENANT_DOMAIN_MODEL = "tenants.Domain"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'de-at'  # 'en-us' #

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locales')
]

LANGUAGES = (
    ('de', _('German')),
    ('en', _('English')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Development static directory
# During development Django serves static files directly from this directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# URL endpoint for Nginx webserver
STATIC_URL = '/statics/'
# Final location for collected static files after collectstatic in Django
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# ---------------------------------------------------------------------------
# S3-compatible object storage (used for post/story image uploads)
#
# Defaults work out-of-the-box with the bundled MinIO container.
#
#   AWS_S3_ENDPOINT_URL        – where boto3 connects (internal). Default: http://minio:9000
#   AWS_S3_PUBLIC_ENDPOINT_URL – base URL embedded in object URLs returned to the browser.
#                                Defaults to AWS_S3_ENDPOINT_URL when not set (correct for
#                                prod/AWS). Set to http://localhost:9000 when running the
#                                backend locally (Option A) so the browser can reach MinIO.
#   AWS_STORAGE_BUCKET_NAME    – bucket name (default: instaclone)
#   AWS_S3_ACCESS_KEY_ID       – access key  (default: minioadmin)
#   AWS_S3_SECRET_ACCESS_KEY   – secret key  (default: minioadmin)
#   AWS_S3_REGION_NAME         – region      (default: us-east-1)
#   AWS_S3_USE_SSL             – true/false  (default: false for MinIO; true for AWS)
#   AWS_S3_VERIFY              – true/false  (default: false for MinIO; true for AWS)
#   AWS_S3_ADDRESSING_STYLE    – path/virtual (default: path; required for MinIO)
# ---------------------------------------------------------------------------
AWS_STORAGE_BUCKET_NAME = environ.get("AWS_STORAGE_BUCKET_NAME", "instaclone")
AWS_S3_REGION_NAME = environ.get("AWS_S3_REGION_NAME", "us-east-1")
AWS_ACCESS_KEY_ID = environ.get("AWS_S3_ACCESS_KEY_ID", "minioadmin")
AWS_SECRET_ACCESS_KEY = environ.get("AWS_S3_SECRET_ACCESS_KEY", "minioadmin")
AWS_S3_ENDPOINT_URL = environ.get("AWS_S3_ENDPOINT_URL", "http://minio:9000")
AWS_S3_ADDRESSING_STYLE = environ.get("AWS_S3_ADDRESSING_STYLE", "path")
AWS_S3_USE_SSL = environ.get("AWS_S3_USE_SSL", "false").lower() == "true"
AWS_S3_VERIFY = environ.get("AWS_S3_VERIFY", "false").lower() == "true"

# AWS_S3_PUBLIC_ENDPOINT_URL controls the hostname embedded in object URLs
# returned to the browser (presigned or plain). It defaults to AWS_S3_ENDPOINT_URL
# so prod/AWS workloads only need the one variable.
# For local dev set it to http://localhost:9000 so the browser can reach MinIO.
AWS_S3_PUBLIC_ENDPOINT_URL = environ.get("AWS_S3_PUBLIC_ENDPOINT_URL", AWS_S3_ENDPOINT_URL)

STORAGES = {
    "default": {
        "BACKEND": "util.storage.PublicEndpointS3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# User uploaded media (workbook images)
# Uploads will go to the /media folder and can be cleared along with the Docker media volume.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'users.User'

# REST Framework settings

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        ['rest_framework.permissions.IsAuthenticated', ]
    )
}

AUTHENTICATION_BACKENDS = [
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
]

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'user.serializers.UserDetailSerializer',
}

SIMPLE_JWT = {
    "USER_ID_FIELD": "username",
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
}

JWT_AUTH = {
    'JWT_VERIFY': True,
    'JWT_EXPIRATION_DELTA': timedelta(days=7),
    'JWT_ALLOW_REFRESH': True
}

REST_USE_JWT = True
REST_SESSION_LOGIN = False
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000
CORS_ALLOW_ALL_ORIGINS = True

BACKEND_URL = "https://c339-2a02-2455-2df-1500-b82e-218f-d0b4-357e.eu.ngrok.io"

ASGI_APPLICATION = "InstaClone.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ['redis://localhost:6379/4']
        }
    },
}

# CKEditor5 Configs

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote',
        ],
        'link': {
            'defaultProtocol': 'https://'
        },
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'removeFormat',
                    'insertTable',],
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
