# Generated by Django 5.1.1 on 2024-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeature',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userfeature',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
