# Generated by Django 5.1.1 on 2024-11-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeature',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
