# Generated by Django 5.1.1 on 2024-11-13 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_userfeature_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature_singular', 'verbose_name_plural': 'feature_plural'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'point_plural', 'verbose_name_plural': 'point_plural'},
        ),
        migrations.AlterModelOptions(
            name='userfeature',
            options={'verbose_name': 'feature_singular', 'verbose_name_plural': 'feature_plural'},
        ),
        migrations.RemoveField(
            model_name='points',
            name='total_points_earned',
        ),
        migrations.AddField(
            model_name='points',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='points_earned'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='feature_cost'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, verbose_name='feature_description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_one_time',
            field=models.BooleanField(default=True, verbose_name='is_one_time'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(unique=True, verbose_name='feature_name'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='points_balance'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='points_spent'),
        ),
        migrations.AlterField(
            model_name='points',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='tasks_completed'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='is_unlocked',
            field=models.BooleanField(default=False, verbose_name='is_unlocked'),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='unlocked_at'),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_features', to=settings.AUTH_USER_MODEL, verbose_name='user_singular'),
        ),
    ]
