# Generated by Django 5.1.1 on 2024-11-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_feature_options_alter_points_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeature',
            options={'verbose_name': 'user_feature_singular', 'verbose_name_plural': 'user_feature_plural'},
        ),
    ]
