# Generated by Django 5.1.1 on 2024-11-20 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_userfeature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='feature_image'),
        ),
        migrations.AddField(
            model_name='feature',
            name='image_upload',
            field=models.FileField(blank=True, help_text='upload_feature_image_help', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('EDIT_AVATAR', 'Edit Avatar')], unique=True, verbose_name='feature_name'),
        ),
    ]
