# Generated by Django 5.1.1 on 2024-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_feature_image_data_feature_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('EDIT_AVATAR', 'Edit Avatar'), ('UNLIMITED_POSTS', 'Unlimited Posts')], unique=True, verbose_name='feature_name'),
        ),
    ]
