# Generated by Django 5.1.1 on 2024-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_alter_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.AddField(
            model_name='points',
            name='total_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='total_tasks'),
        ),
    ]
