# Generated by Django 5.1.1 on 2024-12-23 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0010_remove_feature_description_points_total_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image_upload',
            field=models.FileField(blank=True, help_text='upload_feature_image_help', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='image_upload'),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.feature', verbose_name='feature_singular'),
        ),
    ]
