# Generated by Django 5.1.1 on 2025-03-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0011_alter_feature_image_upload_alter_userfeature_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='is_one_time',
        ),
    ]
