export const WORKBOOK_SECTIONS_REQUEST = 'WORKBOOK_SECTIONS_REQUEST';
export const WORKBOOK_SECTIONS_SUCCESS = 'WORKBOOK_SECTIONS_SUCCESS';
export const WORKBOOK_SECTIONS_FAIL = 'WORKBOOK_SECTIONS_FAIL';
export const WORKBOOK_SECTIONS_RESET = 'WORKBOOK_SECTIONS_RESET';

export const FETCH_USER_POINTS = 'FETCH_USER_POINTS';
export const FETCH_USER_POINTS_FAIL = 'FETCH_USER_POINTS_FAIL';
export const UPDATE_USER_POINTS = 'UPDATE_USER_POINTS';

export const FETCH_FEATURES_REQUEST = 'FETCH_FEATURES_REQUEST';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';
export const FETCH_FEATURES_FAIL = 'FETCH_FEATURES_FAIL';
export const UNLOCK_FEATURE_REQUEST = 'UNLOCK_FEATURE_REQUEST';
export const UNLOCK_FEATURE_SUCCESS = 'UNLOCK_FEATURE_SUCCESS';
export const UNLOCK_FEATURE_FAIL = 'UNLOCK_FEATURE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_FEATURE_ERRORS = 'CLEAR_FEATURE_ERRORS';
