# Generated by Django 4.0.4 on 2023-09-08 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0014_post_content_preview'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportPost',
        ),
        migrations.AlterUniqueTogether(
            name='reportpost',
            unique_together={('reporter', 'post')},
        ),
    ]
